version: '3.8'

services:

  web:
    build: ./src
    command:  "sh -c 'alembic upgrade head  &&  uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000'"
    volumes:
      - .:/usr/src/src
    ports:
      - 8004:8000

    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.3
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_product
    restart: always
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 5s
      timeout: 5s
      retries: 5

  db_test:
    image: postgres:15.3
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_product
    restart: always