version: '3.8'

services:

  web:
    build: ./src
    command:  "sh -c 'alembic upgrade head &&  uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000'"
    volumes:
      - .:/usr/src/src
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo