"""Database creation

Revision ID: 173633b7e97d
Revises: 
Create Date: 2024-04-10 09:40:16.214200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173633b7e97d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False, comment='Внутренний идентификатор категорий'),
    sa.Column('category', sa.String(length=40), nullable=True, comment='Тип категории'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('category_path',
    sa.Column('id', sa.Integer(), nullable=False, comment='Внутренний идентификатор пути категории'),
    sa.Column('category_path', sa.String(length=700), nullable=False, comment='Путь категории'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_path')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False, comment='Внутренний идентификатор города'),
    sa.Column('city', sa.String(length=10), nullable=False, comment='Имя города'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city')
    )
    op.create_table('nomenclature',
    sa.Column('id', sa.Integer(), nullable=False, comment='Внутренний идентификатор номенклатуры'),
    sa.Column('nomenclature', sa.String(length=250), nullable=False, comment='Имя номенклатуры'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomenclature')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False, comment='Внутренний идентификатор продукта'),
    sa.Column('name', sa.String(length=250), nullable=False, comment='Наименования'),
    sa.Column('articul', sa.String(length=40), nullable=False, comment='Артикул'),
    sa.Column('gost', sa.String(length=40), nullable=True, comment='ГОСТ'),
    sa.Column('brand', sa.String(length=40), nullable=True, comment='БРЕНД'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='Внутренний идентификатор категории'),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False, comment='Внутренний идентификатор номенклатуры'),
    sa.Column('category_path_id', sa.Integer(), nullable=False, comment='Внутренний идентификатор категории пути'),
    sa.Column('price', sa.Float(), nullable=False, comment='Цена'),
    sa.Column('url_id', sa.String(length=9), nullable=False, comment='id для формирования url на страницу продукта'),
    sa.Column('warehouse', sa.String(length=80), nullable=True, comment='Изготовитель'),
    sa.Column('instock', sa.String(length=40), nullable=True, comment='Складской статус'),
    sa.Column('city_id', sa.Integer(), nullable=False, comment='Внутренний идентификатор города'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Дата обновления'),
    sa.Column('discount_price', sa.Float(), nullable=True, comment='Цена со скидкой'),
    sa.Column('razmer', sa.String(length=9), nullable=True, comment='Размер'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_path_id'], ['category_path.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('nomenclature')
    op.drop_table('city')
    op.drop_table('category_path')
    op.drop_table('category')
    # ### end Alembic commands ###
